# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('abbr', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='abbreviation')),
                ('found_date', models.DateTimeField(verbose_name='date founded')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='date ended')),
                ('summary', models.TextField(default='', max_length=256, verbose_name='summary')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='logo')),
                ('members', models.IntegerField(default=0, verbose_name='number of members')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='organization email')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('last_modified', models.DateTimeField(auto_now_add=True, null=True, verbose_name='last modified')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
            ],
            options={
                'verbose_name': 'RSO',
                'verbose_name_plural': 'RSOs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('type', models.CharField(choices=[('F', 'FACULTY'), ('A', 'ADMIN'), ('M', 'MODERATOR')], default='M', max_length=1, verbose_name='position type')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='position description')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Organization')),
            ],
            options={
                'verbose_name': 'organization positions',
                'verbose_name_plural': 'organization positions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='tag')),
                ('breadth', models.CharField(choices=[('B', 'BROAD'), ('S', 'SPECIFIC'), ('N', 'NICHE')], default='N', max_length=1, verbose_name='breadth')),
                ('parents', models.ManyToManyField(blank=True, to='app.Tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='tags',
            field=models.ManyToManyField(to='app.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set([('name', 'abbr')]),
        ),
    ]
