# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('caption', models.CharField(max_length=128, verbose_name='caption')),
                ('is_cover', models.BooleanField(default=False, verbose_name='is cover photo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Organization')),
            ],
            options={
                'ordering': ['is_cover'],
                'verbose_name': 'organization photo',
                'verbose_name_plural': 'organization photos',
            },
        ),
        migrations.AlterModelOptions(
            name='organizationposition',
            options={'ordering': ['name'], 'verbose_name': 'organization position', 'verbose_name_plural': 'organization positions'},
        ),
    ]
