# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171202_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='abbr',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='abbreviation'),
        ),
    ]
