# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 21:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_myuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationposition',
            name='holders',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
