# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171211_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='website url'),
        ),
    ]
