# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_organizationposition_holders'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='claimed',
            field=models.BooleanField(default=True, help_text='Designates whether a real person has claimed this account.', verbose_name='claimed'),
        ),
    ]
