# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_myuser_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='category_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='category name'),
        ),
    ]
